### PR TITLE
Image download option enabled

### PR DESCRIPTION
**Pull request by Thilagavathi1**
@ShishirBhandari Could you please verify this PR.if everything looks fine add hacktoberfest-accepted label to this PR and merge it.

### CODE REVIEW

**Comment by ShishirBhandari** [comment]
Did you test it ?

**Comment by Thilagavathi1** [comment]
yes, i can able to download an image.

**Comment by ShishirBhandari** [comment]
Did you test it ?

**Comment by ShishirBhandari** [comment]
> yes, i can able to download an image.

The image is downloaded but the downloaded image doesn't have any content. An empty image is downloaded.

This is a image I downloaded:
mandelbrot_image


Please refer to the file: `js/ui.js` line number 89 to see the current implementation.

**Comment by ShishirBhandari** [comment]
You have resolved the first point, but the second and the third points are more important for this issue.
image

**Comment by Thilagavathi1** [comment]
mandelbrot_image
This is one i have downloaded. For me its downloading correctly in Chrome.

**Comment by Thilagavathi1** [comment]
@ShishirBhandari Could u please explain me what we need to next.

**Comment by Thilagavathi1** [comment]
> @ShishirBhandari Could u please explain me what we need to next.
> 
> @Thilagavathi1,
> Actually, there are these issues: if you zoom or change C-Real and C-imag values and generate a different image, the download button still downloads the default image, not the updated image, and the download button works in some browsers but not in others.
> 
> I looked at the code again and found the way to fix it.
> 
> You just need to do this:
> 
> 1. Go to the file `js/ui.js` and change line number 95:
>    
>    * Remove parenthesis in `downloadCanvasImage()` part.
>    * Test the download button after generating a different image by changing C-real & C-imag values
> 2. You can change the position and style of download button if you wish (not required though).
> 
> Then I think it will be ready to merge.

let me check it

**Comment by Thilagavathi1** [comment]
@ShishirBhandari i have downloaded the image after generating a different image by changing C-real & C-imag values.
and changed button styles.Could u please check this PR. if everything works fine add hactoberfest-accepted label and merge this PR

**Comment by Thilagavathi1** [comment]
@ShishirBhandari Any updates on this PR

**Comment by ShishirBhandari** [comment]
> @ShishirBhandari Any updates on this PR

I have added `hacktoberfest-accepted` label on this PR.

Will merge this once I test it properly.

**Pull request merged**
